In [53]:
yo = weather.sample(n=500).reset_index(drop=True)

In [24]:
yo.to_csv("weatherAUS.csv")

In [59]:
og_df = pd.read_csv("weatherAUS.csv", index_col = 0)
og_df.Date = pd.to_datetime(og_df.Date)

modified_df = og_df.loc[[not x for x in og_df["RainTomorrow"].isnull()]]

def transform_date(x):
    if x < datetime.datetime(2012, 1, 1): 
        return "1. Before 2012"
    elif x < datetime.datetime(2015, 1, 1): 
        return "2. After 2012, Before 2015"
    else:
        return "3. After 2015"
    
modified_df.Date = [transform_date(x) for x in modified_df.Date]

In [67]:
modified_df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,"2. After 2012, Before 2015",Wollongong,15.6,21.9,0.2,NaN,NaN,SE,46.0,WSW,...,58.0,73.0,1021.5,1022.6,NaN,NaN,19.6,18.7,No,No
1,1. Before 2012,Hobart,1.7,12.3,0.4,1.4,8.0,NNW,30.0,N,...,75.0,38.0,1026.0,1022.4,1.0,3.0,4.2,12.2,No,No
2,1. Before 2012,MountGambier,11.7,28.0,0.0,5.2,0.9,SSW,26.0,E,...,89.0,42.0,1009.8,1008.0,7.0,8.0,17.2,26.5,No,Yes
3,"2. After 2012, Before 2015",WaggaWagga,0.4,11.8,0.0,2.6,4.1,WSW,48.0,NNW,...,86.0,54.0,1020.8,1017.6,6.0,5.0,5.6,11.3,No,No
4,1. Before 2012,PerthAirport,18.6,32.6,0.0,12.8,11.7,ENE,44.0,E,...,44.0,36.0,1006.6,1003.2,0.0,7.0,25.1,29.8,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,3. After 2015,Penrith,18.7,31.0,0.0,NaN,NaN,ESE,28.0,S,...,78.0,41.0,NaN,NaN,NaN,NaN,22.8,29.8,No,No
496,1. Before 2012,Watsonia,3.3,16.5,0.2,1.0,6.4,NNE,13.0,NE,...,100.0,68.0,1021.4,1018.8,1.0,6.0,6.7,16.3,No,No
497,3. After 2015,Woomera,17.4,36.0,0.0,NaN,NaN,NNE,39.0,ENE,...,23.0,30.0,1018.5,1014.2,NaN,NaN,27.3,34.7,No,No
498,"2. After 2012, Before 2015",Walpole,9.1,21.0,0.0,NaN,NaN,SSW,30.0,NNE,...,70.0,69.0,1019.4,1016.1,NaN,NaN,16.0,18.7,No,No
499,"2. After 2012, Before 2015",MelbourneAirport,10.0,16.3,2.6,1.0,0.2,WSW,31.0,WSW,...,97.0,72.0,1018.1,1017.7,8.0,7.0,12.4,16.2,Yes,No

In [79]:
df = modified_df
new_df = binary_class.feature_types.cont_to_cat(df.drop("Date", axis=1), True)
new_df["Date"] = df["Date"]

In [84]:
list(binary_class.feature_types.psi(new_df,
                      "RainTomorrow",
                      "Date",
"2. After 2012, Before 2015",
                           "3. After 2015").psi)

[0.6024573756626945,
 0.15809226869173842,
 0.056775737122305256,
 0.013624592156900404,
 0.2345025218921846,
 0.17033273295170107,
 0.13430739281082052,
 0.03464734670419742,
 0.3224620265964764,
 0.09812087671214752,
 0.009674522543387354,
 0.026468739454294933,
 0.03627969465670946,
 0.11139028305901766,
 0.0842814397643875,
 0.03882943099618481,
 0.054284641264211744,
 0.040488456041845144,
 0.06833524924512668,
 0.04451318470561884,
 0.010596661888723668]

In [77]:
binary_class.feature_types.fill_missing(modified_df).to_csv("filledDf.csv")

In [75]:
binary_class.feature_types.cont_to_cat(modified_df, fillNA=True).to_csv("contocatDf.csv")

In [73]:
binary_class.feature_types.labelled_df(modified_df).to_csv("labelledDf.csv")

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,1,47,15.6,21.9,0.2,NaN,NaN,9,46.0,15,...,58.0,73.0,1021.5,1022.6,NaN,NaN,19.6,18.7,0,0
1,0,15,1.7,12.3,0.4,1.4,8.0,6,30.0,3,...,75.0,38.0,1026.0,1022.4,1.0,3.0,4.2,12.2,0,0
2,0,22,11.7,28.0,0.0,5.2,0.9,11,26.0,0,...,89.0,42.0,1009.8,1008.0,7.0,8.0,17.2,26.5,0,1
3,1,42,0.4,11.8,0.0,2.6,4.1,15,48.0,6,...,86.0,54.0,1020.8,1017.6,6.0,5.0,5.6,11.3,0,0
4,0,32,18.6,32.6,0.0,12.8,11.7,1,44.0,0,...,44.0,36.0,1006.6,1003.2,0.0,7.0,25.1,29.8,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2,30,18.7,31.0,0.0,NaN,NaN,2,28.0,8,...,78.0,41.0,NaN,NaN,NaN,NaN,22.8,29.8,0,0
496,0,44,3.3,16.5,0.2,1.0,6.4,5,13.0,4,...,100.0,68.0,1021.4,1018.8,1.0,6.0,6.7,16.3,0,0
497,2,48,17.4,36.0,0.0,NaN,NaN,5,39.0,1,...,23.0,30.0,1018.5,1014.2,NaN,NaN,27.3,34.7,0,0
498,1,43,9.1,21.0,0.0,NaN,NaN,11,30.0,5,...,70.0,69.0,1019.4,1016.1,NaN,NaN,16.0,18.7,0,0
499,1,19,10.0,16.3,2.6,1.0,0.2,15,31.0,15,...,97.0,72.0,1018.1,1017.7,8.0,7.0,12.4,16.2,1,0

In [49]:
binary_class.feature_types.find_type(og_df, "DC")

['Date']

In [74]:
modified_df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,"2. After 2012, Before 2015",Wollongong,15.6,21.9,0.2,NaN,NaN,SE,46.0,WSW,...,58.0,73.0,1021.5,1022.6,NaN,NaN,19.6,18.7,No,No
1,1. Before 2012,Hobart,1.7,12.3,0.4,1.4,8.0,NNW,30.0,N,...,75.0,38.0,1026.0,1022.4,1.0,3.0,4.2,12.2,No,No
2,1. Before 2012,MountGambier,11.7,28.0,0.0,5.2,0.9,SSW,26.0,E,...,89.0,42.0,1009.8,1008.0,7.0,8.0,17.2,26.5,No,Yes
3,"2. After 2012, Before 2015",WaggaWagga,0.4,11.8,0.0,2.6,4.1,WSW,48.0,NNW,...,86.0,54.0,1020.8,1017.6,6.0,5.0,5.6,11.3,No,No
4,1. Before 2012,PerthAirport,18.6,32.6,0.0,12.8,11.7,ENE,44.0,E,...,44.0,36.0,1006.6,1003.2,0.0,7.0,25.1,29.8,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,3. After 2015,Penrith,18.7,31.0,0.0,NaN,NaN,ESE,28.0,S,...,78.0,41.0,NaN,NaN,NaN,NaN,22.8,29.8,No,No
496,1. Before 2012,Watsonia,3.3,16.5,0.2,1.0,6.4,NNE,13.0,NE,...,100.0,68.0,1021.4,1018.8,1.0,6.0,6.7,16.3,No,No
497,3. After 2015,Woomera,17.4,36.0,0.0,NaN,NaN,NNE,39.0,ENE,...,23.0,30.0,1018.5,1014.2,NaN,NaN,27.3,34.7,No,No
498,"2. After 2012, Before 2015",Walpole,9.1,21.0,0.0,NaN,NaN,SSW,30.0,NNE,...,70.0,69.0,1019.4,1016.1,NaN,NaN,16.0,18.7,No,No
499,"2. After 2012, Before 2015",MelbourneAirport,10.0,16.3,2.6,1.0,0.2,WSW,31.0,WSW,...,97.0,72.0,1018.1,1017.7,8.0,7.0,12.4,16.2,Yes,No

In [46]:
column = "Cloud9am"
print(binary_class.feature_types.data_type(og_df, column))
print(binary_class.feature_types.data_type(og_df, column, 10))

NC
N

In [85]:
fa_object = binary_class.feature_analysis(modified_df,
                             "RainTomorrow",
                             "Date",
                             bad_class="Yes")

In [89]:
fa_object.iv_scores("IV")

[0.6645,
 0.0965,
 0.1803,
 0.4124,
 0.1373,
 1.1725,
 0.232,
 0.4716,
 0.2337,
 0.1986,
 0.2184,
 0.2617,
 0.5284,
 1.4659,
 0.4514,
 0.3586,
 0.5495,
 0.7481,
 0.0407,
 0.3072,
 0.4635]

In [12]:
from feature_analysis import binary_class

In [30]:
binary_class.feature_types.cont_to_cat(a).to_csv("contocatDf.csv")

In [ ]:
import feature

In [1]:
import pandas as pd
import datetime
pd.options.mode.chained_assignment = None 

## Data Preprocessing:
weather = pd.read_csv("weatherAUS.csv")
weather.Date = pd.to_datetime(weather.Date)
weather_test = weather.loc[[not x for x in weather["RainTomorrow"].isnull()]]

def transform_date(x):
    if x < datetime.datetime(2012, 1, 1): 
        return "1. Before 2012"
    elif x < datetime.datetime(2015, 1, 1): 
        return "2. After 2012, Before 2015"
    else:
        return "3. After 2015"
    
weather_test.Date = [transform_date(x) for x in weather_test.Date]

In [11]:
import feature_analysis

In [5]:
report.analysis()

,Features,Missing Count,Missing Rate (%),Zero Count,Zero Rate (%),AUC,KS (%),IV
0,Location,0,0.00,0,0.00,0.50,2.03,0.1622
1,MinTemp,637,0.45,156,0.11,0.55,6.84,0.0454
2,MaxTemp,322,0.23,14,0.01,0.61,16.16,0.1373
3,Rainfall,1406,0.99,90275,63.49,0.69,33.39,0.4852
4,Evaporation,60843,42.79,240,0.17,0.54,8.90,0.0609
5,Sunshine,67816,47.69,2308,1.62,0.58,24.48,0.6857
6,WindGustDir,9330,6.56,0,0.00,0.53,6.57,0.0664
7,WindGustSpeed,9270,6.52,0,0.00,0.62,20.57,0.2641
8,WindDir9am,10013,7.04,0,0.00,0.52,6.69,0.0943
9,WindDir3pm,3778,2.66,0,0.00,0.52,5.05,0.0541
10,WindSpeed9am,1348,0.95,8612,6.06,0.55,7.65,0.0388
11,WindSpeed3pm,2630,1.85,1096,0.77,0.55,7.99,0.0435
12,Humidity9am,1774,1.25,1,0.00,0.68,27.80,0.4339
13,Humidity3pm,3610,2.54,4,0.00,0.78,43.70,1.1597
14,Pressure9am,14014,9.86,0,0.00,0.63,21.48,0.2852
15,Pressure3pm,13981,9.83,0,0.00,0.62,19.41,0.2354
16,Cloud9am,53657,37.74,8587,6.04,0.60,22.77,0.4306
17,Cloud3pm,57094,40.15,4957,3.49,0.62,27.38,0.6258
18,Temp9am,904,0.64,35,0.02,0.52,4.49,0.0096
19,Temp3pm,2726,1.92,16,0.01,0.63,19.35,0.2065
20,RainToday,1406,0.99,0,0.00,0.65,30.51,0.5048

In [6]:
import pandas as pd

In [8]:
pd.read_csv("binned_date_df.csv",
                       index_col=0)

,Variable,Metric,"(2008-04-23 23:59:59.999999999, 2010-05-07]","(2010-05-07, 2012-05-06 04:48:00]","(2012-05-06 04:48:00, 2014-04-16 19:12:00]","(2014-04-16 19:12:00, 2015-10-05 04:48:00]","(2015-10-05 04:48:00, 2017-06-12]"
0,Location,psi,NaN,0.51661,0.46158,0.47354,0.57296
1,MinTemp,psi,NaN,0.06418,0.17016,0.16837,0.10635
2,MaxTemp,psi,NaN,0.03063,0.03461,0.12630,0.12239
3,Rainfall,psi,NaN,0.02217,0.08079,0.09575,0.16484
4,Evaporation,psi,NaN,0.16783,0.03323,0.19284,0.53708
5,Sunshine,psi,NaN,0.05707,0.06560,0.09139,0.55011
6,WindGustDir,psi,NaN,0.42015,0.17781,0.36469,0.42557
7,WindGustSpeed,psi,NaN,0.20915,0.07176,0.16591,0.11655
8,WindDir9am,psi,NaN,0.49627,0.52841,0.22710,0.35550
9,WindDir3pm,psi,NaN,0.22120,0.26721,0.40206,0.40756
10,WindSpeed9am,psi,NaN,0.01134,0.02117,0.07663,0.04922
11,WindSpeed3pm,psi,NaN,0.07029,0.04694,0.06781,0.06145
12,Humidity9am,psi,NaN,0.12507,0.15240,0.28940,0.25272
13,Humidity3pm,psi,NaN,0.08915,0.31511,0.37377,0.11513
14,Pressure9am,psi,NaN,0.19116,0.27610,0.22664,0.12205
15,Pressure3pm,psi,NaN,0.24315,0.19299,0.22031,0.17123
16,Cloud9am,psi,NaN,0.05044,0.18717,0.08880,0.17111
17,Cloud3pm,psi,NaN,0.07239,0.12458,0.03577,0.15837
18,Temp9am,psi,NaN,0.04633,0.03499,0.10482,0.07192
19,Temp3pm,psi,NaN,0.04007,0.06915,0.10357,0.09347
20,RainToday,psi,NaN,0.01977,0.15721,0.10976,0.13471